Update action.yaml
Signed-off-by: chahat sagar <109112505+chahatsagarmain@users.noreply.github.com>

diff --git a/.github/actions/verify-metrics-snapshot/action.yaml b/.github/actions/verify-metrics-snapshot/action.yaml
--- a/.github/actions/verify-metrics-snapshot/action.yaml
+++ b/.github/actions/verify-metrics-snapshot/action.yaml
@@ -59,7 +59,9 @@ runs:
       shell: bash
       run: |
         python3 -m pip install prometheus-client
-        if ! python3 ./scripts/e2e/compare_metrics.py --file1 ./.metrics/${{ inputs.snapshot }} --file2 ./.metrics/cached_${{ inputs.snapshot}} --output ./.metrics/diff_${{ inputs.snapshot }}; then 
+        python3 ./scripts/e2e/compare_metrics.py --file1 ./.metrics/${{ inputs.snapshot }} --file2 ./.metrics/cached_${{ inputs.snapshot}} --output ./.metrics/diff_${{ inputs.snapshot }} 
+        if [ $? -eq 0 ]; then
+          echo "No differences found in metrics - failing the job as requested"
           exit 1
         fi
 
